server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import:
      - application-mysql.yml
      - application-jwt.yml
      - application-openapi.yml
      - application-swagger.yml
      - application-iamport.yml

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info

